basic_settings:
  site_title: Ji Hoon. Works
  favicon_image: /images/favicon.png

header_settings:
  logo_image:
  logo_width: 200

menu_settings:
  menu_items:
    - title: "🔥 Projects"
      url: "/"
    - title: "💬 Blog"
      url: "/blog/"
    - title: "👀 About"
      url: "/about"
    - title: "📮 Contact"
      url: "/contact"

footer_settings:
  logo_image:
  logo_width: 200
  footer_tagline: good9395@gmail.com

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 10

contact_settings:
  form_action: "https://formspree.io/good9395@gmail.com"
  confirmation_url: "/thanks"
  email_subject: "Contact form submission"
  send_button_text: "Send Message"

social_settings:
  facebook_url: ""
  twitter_url: ""
  instagram_url: "https://www.instagram.com/jihoon__c/"
  snapchat_url: ""
  youtube_url: ""
  google-plus_url: ""
  vimeo_url: ""
  pinterest_url: "https://www.pinterest.co.kr/Ji_Hoon_Yu/_saved/"
  medium_url: ""
  quora_url: ""
  amazon_url: ""
  apple_url: ""
  android_url: ""
  tumblr_url: ""
  dribbble_url: ""
  behance_url: "https://www.behance.net/yujihoon"
  deviantart_url: ""
  github_url: "https://github.com/YuJiHoon"
  reddit_url: ""
  flickr_url: ""
  etsy_url: ""
  kickstarter_url: ""
  soundcloud_url: ""
  spotify_url: ""
  bandcamp_url: ""
  linkedin_url: "https://www.linkedin.com/in/%EC%A7%80%ED%9B%88-%EC%9C%A0-98598b149/"

color_settings:
  background_color: "#000000"
  background_alt_color: "#000000"
  text_dark_color: "#ffffff"
  text_medium_color: "#b8bfc4"
  text_light_color: "#ABB7B7"
  accent_color: "#0A84ff"
  border_color: "#dddddd"
  overlay_background_color: "#0A84ff"
  overlay_text_color: "#ffffff"
  overlay_accent_color: "#2A2F36"
  error_color: "#FF453A"

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&family=Roboto:wght@100;300;400;500;700;900" rel="stylesheet">'
  title_font: '"Roboto", sans-serif'
  body_font: '"Noto Sans KR", sans-serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 25
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 20
    weight: 600
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 600
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0

  h1:
    small_size: 24
    medium_size: 35
    large_size: 26
    weight: 700
    letter_spacing: -0.01
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 22
    weight: 700
    letter_spacing: -0.01
    line_height: 1.2
  h3:
    small_size: 17
    medium_size: 25
    large_size: 17
    weight: 700
    letter_spacing: -0.01
    line_height: 1.2
  h4:
    small_size: 19
    medium_size: 22
    large_size: 19
    weight: 500
    letter_spacing: -0.01
    line_height: 1.2
  h5:
    small_size: 17
    medium_size: 20
    large_size: 17
    weight: 500
    letter_spacing: -0.01
    line_height: 1.2
  h6:
    small_size: 16
    medium_size: 20
    large_size: 16
    weight: 900
    letter_spacing: -0.01
    line_height: 1.2
  p:
    small_size: 16
    medium_size: 17
    large_size: 16
    weight: 400
    letter_spacing: -0
    line_height: 1.7
  blockquote:
    small_size: 18
    medium_size: 35
    large_size: 18
    weight: 700
    letter_spacing: -0.031
    line_height: 1.8
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
